### ISSUE TITLE
make fails with: p2x.cc:2020:49: error: ‘it’ was not declared in this scope

### ISSUE THREAD

**Issue by gdimopoulos** [rainac/p2x#1]
I ran ./bootstrap, ./configure and make -j install as per the INSTALLATION instructions.
I receive the error in the title. I am compiling on armv7 linux with 4.9-12-sunxi kernel.

**Comment by rainac** [comment]
Hi,

I am not getting this exact same error, but it I think the issue is that the Flex-generated code is out of date.

Can you try "make distclean", this will delete the generated files.

Then again ./configure and make.

Best regards

**Comment by gdimopoulos** [comment]
I tried the distclean but no luck
I noticed there are errors before that, that might be the cause of the problem.

> make  all-recursive
> make[1]: Entering directory '/home/volumio/p2x'
> ./vcs-version.sh > svn-version.txt.tmp; \
> if ! diff svn-version.txt.tmp svn-version.txt > /dev/null; then cp svn-version.txt.tmp svn-version.txt; else echo "svn-version.txt is unchanged"; fi; \
> rm svn-version.txt.tmp
> svn-version.txt is unchanged
> Making all in src
> make[2]: Entering directory '/home/volumio/p2x/src'
> g++ -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT p2x-p2x.o -MD -MP -MF .deps/p2x-p2x.Tpo -c -o p2x-p2x.o `test -f 'p2x.cc' || echo './'`p2x.cc
> p2x.cc: In member function ‘void TokenInfo::addRBraces(TokenProto&)’:
> p2x.cc:401:15: error: ‘it’ does not name a type
>      for (auto it = tp.endList.begin(); it != tp.endList.end(); ++it) {
>                ^
> p2x.cc:401:40: error: expected ‘;’ before ‘it’
>      for (auto it = tp.endList.begin(); it != tp.endList.end(); ++it) {
>                                         ^
> p2x.cc:401:40: error: ‘it’ was not declared in this scope
> In file included from p2x.cc:1517:0:
> TreePrintHelperMatlabChildren.hh: At global scope:
> TreePrintHelperMatlabChildren.hh:31:10: error: ‘function’ in namespace ‘std’ does not name a template type
>      std::function<void(Token const *t)> m_fcn;
>           ^
> TreePrintHelperMatlabChildren.hh:33:69: error: ‘std::function’ has not been declared
>      TermCollector(TreePrintHelperMATLABChildren const &m_cont, std::function<void(Token const *t)> fcn) :
>                                                                      ^
> TreePrintHelperMatlabChildren.hh:33:77: error: expected ‘,’ or ‘...’ before ‘<’ token
>      TermCollector(TreePrintHelperMATLABChildren const &m_cont, std::function<void(Token const *t)> fcn) :
>                                                                              ^
> TreePrintHelperMatlabChildren.hh:71:50: error: ‘std::function’ has not been declared
>    virtual void collectTerms(Token const *t, std::function<void(Token const *t)> fcn) {
>                                                   ^
> TreePrintHelperMatlabChildren.hh:71:58: error: expected ‘,’ or ‘...’ before ‘<’ token
>    virtual void collectTerms(Token const *t, std::function<void(Token const *t)> fcn) {
>                                                           ^
> TreePrintHelperMatlabChildren.hh:84:64: error: ‘std::function’ has not been declared
>    bool andChildren(std::list<Token const*> const &sterms, std::function<bool(Token const *t)> fcn) {
>                                                                 ^
> TreePrintHelperMatlabChildren.hh:84:72: error: expected ‘,’ or ‘...’ before ‘<’ token
>    bool andChildren(std::list<Token const*> const &sterms, std::function<bool(Token const *t)> fcn) {
>                                                                         ^
> TreePrintHelperMatlabChildren.hh:94:49: error: ‘std::function’ has not been declared
>                    std::string const &name, std::function<ValueType (Token const *t)> fcn,
>                                                  ^
> TreePrintHelperMatlabChildren.hh:94:57: error: expected ‘,’ or ‘...’ before ‘<’ token
>                    std::string const &name, std::function<ValueType (Token const *t)> fcn,
>                                                          ^
> TreePrintHelperMatlabChildren.hh: In constructor ‘TreeXMLWriter::TreePrintHelperMATLABChildren::TermCollector::TermCollector(const TreeXMLWriter::TreePrintHelperMATLABChildren&, int)’:
> TreePrintHelperMatlabChildren.hh:35:7: error: class ‘TreeXMLWriter::TreePrintHelperMATLABChildren::TermCollector’ does not have any field named ‘m_fcn’
>        m_fcn(fcn)
>        ^
> TreePrintHelperMatlabChildren.hh:35:13: error: ‘fcn’ was not declared in this scope
>        m_fcn(fcn)
>              ^
> TreePrintHelperMatlabChildren.hh: In member function ‘int TreeXMLWriter::TreePrintHelperMATLABChildren::TermCollector::onEnter(const Token*, const Token*)’:
> TreePrintHelperMatlabChildren.hh:48:22: error: ‘m_fcn’ was not declared in this scope
>          m_fcn(t->left);
>                       ^
> TreePrintHelperMatlabChildren.hh: In member function ‘int TreeXMLWriter::TreePrintHelperMATLABChildren::TermCollector::onContent(const Token*, const Token*)’:
> TreePrintHelperMatlabChildren.hh:62:23: error: ‘m_fcn’ was not declared in this scope
>          m_fcn(t->right);
>                        ^
> TreePrintHelperMatlabChildren.hh: In member function ‘virtual void TreeXMLWriter::TreePrintHelperMATLABChildren::collectTerms(const Token*, int)’:
> TreePrintHelperMatlabChildren.hh:72:40: error: ‘fcn’ was not declared in this scope
>      TermCollector termCollector(*this, fcn);
>                                         ^
> TreePrintHelperMatlabChildren.hh: In member function ‘virtual void TreeXMLWriter::TreePrintHelperMATLABChildren::collectChildren(const Token*, std::list<const Token*>&)’:
> TreePrintHelperMatlabChildren.hh:77:72: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>      collectTerms(t, [&](Token const *t) -> void { sterms.push_back(t); });
>                                                                         ^
> TreePrintHelperMatlabChildren.hh:77:73: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::collectTerms(const Token*&, TreeXMLWriter::TreePrintHelperMATLABChildren::collectChildren(const Token*, std::list<const Token*>&)::<lambda(const Token*)>)’
>      collectTerms(t, [&](Token const *t) -> void { sterms.push_back(t); });
>                                                                          ^
> TreePrintHelperMatlabChildren.hh:77:73: note: candidate is:
> TreePrintHelperMatlabChildren.hh:71:16: note: virtual void TreeXMLWriter::TreePrintHelperMATLABChildren::collectTerms(const Token*, int)
>    virtual void collectTerms(Token const *t, std::function<void(Token const *t)> fcn) {
>                 ^
> TreePrintHelperMatlabChildren.hh:71:16: note:   no known conversion for argument 2 from ‘TreeXMLWriter::TreePrintHelperMATLABChildren::collectChildren(const Token*, std::list<const Token*>&)::<lambda(const Token*)>’ to ‘int’
> TreePrintHelperMatlabChildren.hh: In member function ‘bool TreeXMLWriter::TreePrintHelperMATLABChildren::andChildren(const std::list<const Token*>&, int)’:
> TreePrintHelperMatlabChildren.hh:86:15: error: ‘it’ does not name a type
>      for (auto it = sterms.begin(); it != sterms.end(); ++it) {
>                ^
> TreePrintHelperMatlabChildren.hh:86:36: error: expected ‘;’ before ‘it’
>      for (auto it = sterms.begin(); it != sterms.end(); ++it) {
>                                     ^
> TreePrintHelperMatlabChildren.hh:86:36: error: ‘it’ was not declared in this scope
> TreePrintHelperMatlabChildren.hh:87:39: error: ‘fcn’ was not declared in this scope
>        res = res && (not *it or fcn(*it));
>                                        ^
> TreePrintHelperMatlabChildren.hh: In member function ‘void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)’:
> TreePrintHelperMatlabChildren.hh:97:15: error: ‘it’ does not name a type
>      for (auto it = sterms.begin(); it != sterms.end(); ++it) {
>                ^
> TreePrintHelperMatlabChildren.hh:97:36: error: expected ‘;’ before ‘it’
>      for (auto it = sterms.begin(); it != sterms.end(); ++it) {
>                                     ^
> TreePrintHelperMatlabChildren.hh:97:36: error: ‘it’ was not declared in this scope
> TreePrintHelperMatlabChildren.hh:98:30: error: there are no arguments to ‘fcn’ that depend on a template parameter, so a declaration of ‘fcn’ must be available [-fpermissive]
>        ValueType val = fcn(*it);
>                               ^
> TreePrintHelperMatlabChildren.hh:98:30: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
> TreePrintHelperMatlabChildren.hh:102:10: error: ‘nend’ does not name a type
>      auto nend = std::unique(vterms2.begin(), vterms2.end());
>           ^
> TreePrintHelperMatlabChildren.hh:103:5: error: ‘function’ is not a member of ‘std’
>      std::function<void(ValueType const &v)> fprint = [&](ValueType const &val) -> void {
>      ^
> TreePrintHelperMatlabChildren.hh:103:19: error: expected primary-expression before ‘void’
>      std::function<void(ValueType const &v)> fprint = [&](ValueType const &val) -> void {
>                    ^
> TreePrintHelperMatlabChildren.hh:118:9: error: ‘nend’ was not declared in this scope
>      if (nend == vterms2.begin()+1 and compress) {
>          ^
> TreePrintHelperMatlabChildren.hh:118:39: error: ‘compress’ was not declared in this scope
>      if (nend == vterms2.begin()+1 and compress) {
>                                        ^
> TreePrintHelperMatlabChildren.hh:122:13: error: ‘pcomma’ was not declared in this scope
>          if (pcomma) {
>              ^
> TreePrintHelperMatlabChildren.hh:130:11: error: ‘pcomma’ was not declared in this scope
>        if (pcomma) {
>            ^
> TreePrintHelperMatlabChildren.hh:134:17: error: ‘it’ does not name a type
>        for (auto it = vterms.begin(); it != vterms.end(); ++it) {
>                  ^
> TreePrintHelperMatlabChildren.hh:134:38: error: expected ‘;’ before ‘it’
>        for (auto it = vterms.begin(); it != vterms.end(); ++it) {
>                                       ^
> TreePrintHelperMatlabChildren.hh:134:38: error: ‘it’ was not declared in this scope
> TreePrintHelperMatlabChildren.hh: In member function ‘virtual int TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)’:
> TreePrintHelperMatlabChildren.hh:201:113: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>        printTerms<std::string>(t, sterms, "n", [&](Token const *t) -> std::string { return t ? elemName(t) : ""; }, true, false);
>                                                                                                                  ^
> TreePrintHelperMatlabChildren.hh:201:127: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*&, std::list<const Token*>&, const char [2], TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>, bool, bool)’
>        printTerms<std::string>(t, sterms, "n", [&](Token const *t) -> std::string { return t ? elemName(t) : ""; }, true, false);
>                                                                                                                                ^
> TreePrintHelperMatlabChildren.hh:201:127: note: candidate is:
> TreePrintHelperMatlabChildren.hh:93:8: note: template<class ValueType> void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)
>    void printTerms(Token const *, std::list<Token const*> const &sterms,
>         ^
> TreePrintHelperMatlabChildren.hh:93:8: note:   template argument deduction/substitution failed:
> TreePrintHelperMatlabChildren.hh:201:127: note:   cannot convert ‘<lambda closure object>TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>{((TreeXMLWriter::TreePrintHelperMATLABChildren*)this)}’ (type ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’) to type ‘int’
>        printTerms<std::string>(t, sterms, "n", [&](Token const *t) -> std::string { return t ? elemName(t) : ""; }, true, false);
>                                                                                                                                ^
> TreePrintHelperMatlabChildren.hh:202:112: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>        printTerms<std::string>(t, sterms, "t", [&](Token const *t) -> std::string { return t ? getText(t) : ""; }, true, true, false);
>                                                                                                                 ^
> TreePrintHelperMatlabChildren.hh:202:132: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*&, std::list<const Token*>&, const char [2], TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>, bool, bool, bool)’
>        printTerms<std::string>(t, sterms, "t", [&](Token const *t) -> std::string { return t ? getText(t) : ""; }, true, true, false);
>                                                                                                                                     ^
> TreePrintHelperMatlabChildren.hh:202:132: note: candidate is:
> TreePrintHelperMatlabChildren.hh:93:8: note: template<class ValueType> void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)
>    void printTerms(Token const *, std::list<Token const*> const &sterms,
>         ^
> TreePrintHelperMatlabChildren.hh:93:8: note:   template argument deduction/substitution failed:
> TreePrintHelperMatlabChildren.hh:202:132: note:   cannot convert ‘<lambda closure object>TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>{((TreeXMLWriter::TreePrintHelperMATLABChildren*)this)}’ (type ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’) to type ‘int’
>        printTerms<std::string>(t, sterms, "t", [&](Token const *t) -> std::string { return t ? getText(t) : ""; }, true, true, false);
>                                                                                                                                     ^
> TreePrintHelperMatlabChildren.hh:203:114: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>        printTerms<std::string>(t, sterms, "i", [&](Token const *t) -> std::string { return t ? getIgnore(t) : ""; }, true);
>                                                                                                                   ^
> TreePrintHelperMatlabChildren.hh:203:121: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*&, std::list<const Token*>&, const char [2], TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>, bool)’
>        printTerms<std::string>(t, sterms, "i", [&](Token const *t) -> std::string { return t ? getIgnore(t) : ""; }, true);
>                                                                                                                          ^
> TreePrintHelperMatlabChildren.hh:203:121: note: candidate is:
> TreePrintHelperMatlabChildren.hh:93:8: note: template<class ValueType> void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)
>    void printTerms(Token const *, std::list<Token const*> const &sterms,
>         ^
> TreePrintHelperMatlabChildren.hh:93:8: note:   template argument deduction/substitution failed:
> TreePrintHelperMatlabChildren.hh:203:121: note:   cannot convert ‘<lambda closure object>TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>{((TreeXMLWriter::TreePrintHelperMATLABChildren*)this)}’ (type ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’) to type ‘int’
>        printTerms<std::string>(t, sterms, "i", [&](Token const *t) -> std::string { return t ? getIgnore(t) : ""; }, true);
>                                                                                                                          ^
> TreePrintHelperMatlabChildren.hh:205:97: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>          printTerms<int>(t, sterms, "ln", [&](Token const *t) -> int { return (t ? t->line : 0); });
>                                                                                                  ^
> TreePrintHelperMatlabChildren.hh:205:98: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*&, std::list<const Token*>&, const char [3], TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>)’
>          printTerms<int>(t, sterms, "ln", [&](Token const *t) -> int { return (t ? t->line : 0); });
>                                                                                                   ^
> TreePrintHelperMatlabChildren.hh:205:98: note: candidate is:
> TreePrintHelperMatlabChildren.hh:93:8: note: template<class ValueType> void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)
>    void printTerms(Token const *, std::list<Token const*> const &sterms,
>         ^
> TreePrintHelperMatlabChildren.hh:93:8: note:   template argument deduction/substitution failed:
> TreePrintHelperMatlabChildren.hh:205:98: note:   cannot convert ‘<lambda closure object>TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>{}’ (type ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’) to type ‘int’
>          printTerms<int>(t, sterms, "ln", [&](Token const *t) -> int { return (t ? t->line : 0); });
>                                                                                                   ^
> TreePrintHelperMatlabChildren.hh:207:99: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>          printTerms<int>(t, sterms, "cl", [&](Token const *t) -> int { return (t ? t->column : 0); });
>                                                                                                    ^
> TreePrintHelperMatlabChildren.hh:207:100: error: no matching function for call to ‘TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*&, std::list<const Token*>&, const char [3], TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>)’
>          printTerms<int>(t, sterms, "cl", [&](Token const *t) -> int { return (t ? t->column : 0); });
>                                                                                                     ^
> TreePrintHelperMatlabChildren.hh:207:100: note: candidate is:
> TreePrintHelperMatlabChildren.hh:93:8: note: template<class ValueType> void TreeXMLWriter::TreePrintHelperMATLABChildren::printTerms(const Token*, const std::list<const Token*>&, const string&, int)
>    void printTerms(Token const *, std::list<Token const*> const &sterms,
>         ^
> TreePrintHelperMatlabChildren.hh:93:8: note:   template argument deduction/substitution failed:
> TreePrintHelperMatlabChildren.hh:207:100: note:   cannot convert ‘<lambda closure object>TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>{}’ (type ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’) to type ‘int’
>          printTerms<int>(t, sterms, "cl", [&](Token const *t) -> int { return (t ? t->column : 0); });
>                                                                                                     ^
> TreePrintHelperMatlabChildren.hh:209:112: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
>        bool allItems = andChildren(sterms, [&](Token const *t) -> bool { return t->left == 0 and t->right == 0; });
>                                                                                                                 ^
> TreePrintHelperMatlabChildren.hh:209:113: error: invalid user-defined conversion from ‘TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>’ to ‘int’ [-fpermissive]
>        bool allItems = andChildren(sterms, [&](Token const *t) -> bool { return t->left == 0 and t->right == 0; });
>                                                                                                                  ^
> TreePrintHelperMatlabChildren.hh:209:66: note: candidate is: TreeXMLWriter::TreePrintHelperMATLABChildren::onEnter(const Token*, const Token*)::<lambda(const Token*)>::operator bool (*)(const Token*)() const <near match>
>        bool allItems = andChildren(sterms, [&](Token const *t) -> bool { return t->left == 0 and t->right == 0; });
>                                                                   ^
> TreePrintHelperMatlabChildren.hh:209:66: note:   no known conversion from ‘bool (*)(const Token*)’ to ‘int’
> p2x.cc: In function ‘bool parseConfig(Lexer&, const string&, const Token*, TokenInfo&)’:
> p2x.cc:2020:23: error: ‘it’ does not name a type
>              for (auto it = tp->endList.begin(); it != tp->endList.end(); ++it) {
>                        ^
> p2x.cc:2020:49: error: expected ‘;’ before ‘it’
>              for (auto it = tp->endList.begin(); it != tp->endList.end(); ++it) {
>                                                  ^
> p2x.cc:2020:49: error: ‘it’ was not declared in this scope
> Makefile:483: recipe for target 'p2x-p2x.o' failed
> make[2]: *** [p2x-p2x.o] Error 1
> make[2]: Leaving directory '/home/volumio/p2x/src'
> Makefile:446: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/volumio/p2x'
> Makefile:365: recipe for target 'all' failed
> make: *** [all] Error 2
> 

Thanks in advance.

**Comment by rainac** [comment]
Okay, my next guess is that the C++ compiler does not understand the new C++ 11. Because it fails after the "auto" keyword. Can you try adding the relevant flag to CXXFLAGS before ./configure, like this:

CXXFLAGS="-std=gnu++11" ./configure
make

I will try to detect this in the configure script, for the future

**Comment by rainac** [comment]
Hi, I hope the issue is fixed in the latest version

**Comment by gdimopoulos** [comment]
Hi rainac, that worked like a charm! 
Thank you very much for your help!
